# Write your MySQL query statement below
SELECT PROJECT.PROJECT_ID, ROUND(AVG(EMPLOYEE.EXPERIENCE_YEARS), 2) AS AVERAGE_YEARS
FROM PROJECT
LEFT JOIN EMPLOYEE ON PROJECT.EMPLOYEE_ID = EMPLOYEE.EMPLOYEE_ID
GROUP BY PROJECT.PROJECT_ID ;